// data/experience.js
export const workExperiences = [
  {
    company: "Tesco",
    title: "Retail Planner",
    years: "Oct 2023 - Present",
    description: [
      "Developed design packs for large-format and convenience stores, aligning with Tesco’s brand and spatial standards.",
      "Created presentation graphics and layouts to facilitate collaboration across Central Europe and UK teams.",
      "Worked with Costing, SRM and Format teams on feasibility studies and store renewals.",
      "Applied graphic principles (typography, layout, brand colors) to enhance visual communication.",
    ],
    skills: [
      "Spatial Planning",
      "Visual Design",
      "Graphic Communication & Storytelling",
      "Design Ideation & Concept Development",
      "Branding & Layout Design",
      "Project Coordination 3D Rendering & Visualization",
    ],
    companyLogo: "/tesco.jpg",
  },
  {
    company: "Ashkam",
    title: "Graphic Designer & Architect",
    years: "May 2023 - September 2023",
    description: [
      "Designed branded content including brochures, menu cards, and client presentations.",
      "Created mood boards, color palettes and layout compositions for high-end interiors.",
      "Applied typography, color theory and material texture in print and digital formats.",
      "Supported architectural concepts with visually driven communication tools.",
    ],
    skills: [
      "Visual Design",
      "Color Theory & Typography",
      "Graphic Communication & Storytelling",
      "Design Ideation & Concept Development",
      "Spatial Planning",
      "Branding & Layout Design",
      "Project Coordination 3D Rendering & Visualization",
    ],
    companyLogo: "/ashkam.jpeg",
  },
  {
    company: "Freelance ",
    title: "Graphic & Spatial Designer",
    years: "Apr 2022- May 2023",
    description: [
      "Delivered branding and visual identity solutions for boutique interior and architecture clients.",
      "Created print-ready assets, presentation templates and digital brochures aligned with design narratives.",
      "Merged architectural concepts with visual storytelling to communicate design intent.",
      "Led mood board creation and brand style development for lifestyle-focused residential projects.",
    ],
    skills: [
      "Spatial Planning",
      "Proposal Writing & Documentation",
      "Content Development & Communication",
      "Client-Focused Visual Narratives",
      "Color Theory & Typography",
      "Branding & Layout Design",
      "Project Coordination 3D Rendering & Visualization",
    ],
    companyLogo: "",
  },
  {
    company: "buildAhome ",
    title: "Architect & Visual Communication Designer",
    years: "Jan 2021- March 2022",
    description: [
      "Managed project documentation, including client decks, handover presentations and marketing visuals.",
      "Developed mood boards and spatial brand language for 30+ residential projects.",
      "Integrated visual design elements into architecture to enhance client engagement.",
    ],
    skills: [
      "Spatial Planning",
      "Physical Modeling",
      "Visual Design",
      "Graphic Communication & Storytelling",
      "Design Ideation & Concept Development",
      "Branding & Layout Design",
      "Project Coordination 3D Rendering & Visualization",
    ],
    companyLogo: "/buildahome.webp",
  },
];

export const exteriorProjects = [
  {
    id: 1,
    name: "Mr. Jagadish's residence",
    images: [
      "/jagadish-residence/16.jpeg",
      "/jagadish-residence/02.jpg",
      "/jagadish-residence/001.jpg",
      "/jagadish-residence/002.jpg",
      "/jagadish-residence/03.jpg",
      "/jagadish-residence/04.jpg",
      "/jagadish-residence/07.jpg",
      "/jagadish-residence/08.jpg",
      "/jagadish-residence/09.jpg",
      "/jagadish-residence/11.jpg",
      "/jagadish-residence/12.jpg",
      "/jagadish-residence/13.jpg",
      "/jagadish-residence/14.jpg",
      "/jagadish-residence/15.jpg",
    ],
    shortDescription: "1200 sq.ft | Bengaluru | Karnataka",
    description:
      "This Vastu-compliant project is designed on a 30’ x 40’ east-facing plot, combining an office space on the ground floor with a 3BHK duplex above. Prioritizing natural light and ventilation, the building features large windows and multiple skylights. The façade, constrained by area and height restrictions, adopts a minimalist approach with a modern finish using Fundermax panels and stone cladding. The double-height living area enhances spatial volume, creating an expansive feel. Interiors are designed with a light color palette to maximize brightness and openness.",
    additionalInfo: {
      status: "Completed",
      location: "Ozone Urbana",
      structure: "G+2",
      plotArea: "1,200 sq.ft",
      builtupArea: "5,270 sq.ft",
      type: "Residential + Office Duplex",
      vastu: "Compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 2,
    name: "Mrs. Sahana Arun residence",
    images: [
      "/sahana-residence/002.jpg",
      "/sahana-residence/01.jpeg",
      "/sahana-residence/02.jpeg",
      "/sahana-residence/03.jpeg",
      "/sahana-residence/04.jpeg",
      "/sahana-residence/05.jpeg",
      "/sahana-residence/06.jpeg",
      "/sahana-residence/7.jpeg",
      "/sahana-residence/07.jpeg",
      "/sahana-residence/08.jpeg",
      "/sahana-residence/09.jpeg",
      "/sahana-residence/10.jpeg",
      "/sahana-residence/11.jpeg",
      "/sahana-residence/12.jpeg",
      "/sahana-residence/13.jpeg",
      "/sahana-residence/14.jpeg",
      "/sahana-residence/15.jpeg",
      "/sahana-residence/16.jpeg",
    ],
    shortDescription: "2530 sq.ft | Bengaluru | Karnataka",
    description:
      "Designed on a 2530 sq.ft south-facing site, this 5-bedroom residence embraces climate-conscious living through its construction using Compressed Earth Blocks (CEBs)—a material that lends both environmental responsibility and tactile warmth to the architecture. At the heart of the home is a triple-height volume that allows light to cascade through levels, creating openness and visual drama. An internal waterbody subtly divides the public and private zones—separating the living room from the puja space and kitchen—not as a wall, but as a fluid threshold that preserves visual connection and a sense of continuity across the home. The kitchen opens into the outdoors through a large panoramic window, while multiple balconies and a private plunge pool extend the living experience into nature. Every element—from material to form—has been curated to create a home that is rooted, refined, and responsive to its context.",
    additionalInfo: {
      status: "Completed",
      location: "Bengaluru",
      structure: "G+2",
      plotArea: "1,200 sq.ft",
      builtupArea: "5,015 sq.ft",
      type: "Residential",
      vastu: "Compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 3,
    name: "Mr. Kalyan's residence",
    images: [
      "/kalyan-residence/001.jpg",
      "/kalyan-residence/2.jpg",
      "/kalyan-residence/3.jpeg",
      "/kalyan-residence/3.jpg",
      "/kalyan-residence/3A.jpeg",
      "/kalyan-residence/4.jpeg",
      "/kalyan-residence/5.jpg",
      "/kalyan-residence/6.jpg",
      "/kalyan-residence/7.jpeg",
    ],
    shortDescription: "3000 sq.ft | Bengaluru | Karnataka",
    description:
      "A 4BHK Villa – Nandi Hills Set against the scenic backdrop of Nandi Hills, this Vastu-compliant 4BHK villa spans three thoughtfully designed levels. The ground floor features a welcoming foyer, bright living room, puja room, two bedrooms, and an open kitchen-dining area that opens directly to the garden. A staircase and lift provide vertical connectivity to the upper floors, enhancing seamless movement throughout the home. The first floor includes a bedroom, home theatre, family room, and a multi-purpose hall opening onto a deep L-shaped balcony with expansive views and ample ventilation. The terrace floor offers a versatile room, ideal for a studio, office, or guest suite. Sustainable Athangudi tiles and hollow clay blocks provide thermal comfort, durability, and timeless charm. This villa exemplifies a harmonious blend of tradition, comfort, and conscious design.",
    additionalInfo: {
      status: "Completed",
      location: "Bengaluru",
      structure: "G+1.5",
      plotArea: "3000 sq.ft",
      builtupArea: "3,612 sq.ft",
      type: "Residential ",
      vastu: "Compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 4,
    name: "Mr. Mohan's residence",
    images: [
      "/mohan-residence/01.jpeg",
      "/mohan-residence/02.jpeg",
      "/mohan-residence/1.jpeg",
      "/mohan-residence/2.jpeg",
      "/mohan-residence/3.jpeg",
      "/mohan-residence/4.jpeg",
      "/mohan-residence/5.jpeg",
      "/mohan-residence/6.jpeg",
      "/mohan-residence/7.jpeg",
      "/mohan-residence/8.jpeg",
      "/mohan-residence/9.jpg",
    ],
    shortDescription: "1200 sq.ft | Bengaluru | Karnataka",
    description:
      "Set on a compact 30x40 plot, this G+1 residence brings together traditional aesthetics with thoughtful spatial planning. Designed with 3 bedrooms, the home opens up into a warm and welcoming living space accentuated by a double-height ceiling and a skylight that floods the core with natural light. The structure incorporates filler slabs, offering both visual interest and material efficiency. Echoing a sense of heritage, the interiors feature wooden columns, soft arches, and curated niches along the staircase—perfect for showcasing handcrafted artifacts and heirlooms. Rooted in tradition yet responsive to contemporary needs, this residence blends craftsmanship, light, and volume to create a home that feels both grounded and graceful.",
    additionalInfo: {
      status: "Completed",
      location: "Bengaluru",
      structure: "G + 1",
      plotArea: "1,200 sq.ft",
      builtupArea: "2,015 sq.ft",
      type: "Residential ",
      vastu: "Compliant",
    },
    video: "/mohan-residence/video.mp4",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 5,
    name: "Mr. Abhijith's residence",
    images: [
      "/abhijith-residence/01.jpg",
      "/abhijith-residence/001.jpg",
      "/abhijith-residence/02.jpg",
      "/abhijith-residence/03.jpg",
      "/abhijith-residence/04.jpg",
      "/abhijith-residence/05.jpg",
      "/abhijith-residence/06.jpg",
    ],
    shortDescription: "1744 sq.ft | Bengaluru | Karnataka",
    description:
      "Designed and built on a 29'6 x 59'1’ north-facing plot, this spacious 3BHK home features two courtyards—one on each level—each topped with skylights to maximize natural light and ventilation. The courtyards create a seamless connection between the two floors, enhancing openness and airflow throughout the house. The design prioritizes simplicity, space, and functionality to meet the client’s requirements for comfortable modern living. Instead of blockwork, perforated sheets are used on either side to support the skylight glass, allowing hot air to escape and keeping the interior cooler.",
    additionalInfo: {
      status: "Completed",
      location: "Bengaluru",
      structure: "G+2",
      plotArea: "1744 sq.ft",
      builtupArea: "4500 sq.ft",
      type: "Residential ",
      vastu: "Compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 6,
    name: "Mr. Raghavendra's residence",
    images: [
      "/raghavendra-residence/1.jpg",
      "/raghavendra-residence/02.jpg",
      "/raghavendra-residence/03.jpg",
      "/raghavendra-residence/04.jpg",
      "/raghavendra-residence/05.jpg",
      "/raghavendra-residence/06.jpg",
      "/raghavendra-residence/07.jpg",
    ],
    shortDescription: "1200 sq.ft | Bengaluru | Karnataka",
    description:
      "Designed on a 30’x40′ east-facing plot, this G+2 residence follows the principles of Vastu Shastra, ensuring harmony, balance, and spatial clarity throughout. The ground floor accommodates a dedicated art room, providing a serene space for creative expression. The first and second floors form a duplex residence, carefully planned for comfortable living. A key highlight of the home is the double-height space over the puja room, allowing light to flow in and emphasizing the spiritual core of the home—both visually and emotionally. Every element—from the vertical planning to the functional zoning—reflects an efficient use of space while maintaining openness and connectivity. With its blend of traditional sensibilities and modern needs, this residence offers grounded, intentional living in an urban setting.",
    additionalInfo: {
      status: "Completed",
      location: "Bengaluru",
      structure: "G + 2",
      plotArea: "1,200 sq.ft",
      builtupArea: "3,030 sq.ft",
      type: "Residential",
      vastu: "Compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 7,
    name: "Mr. Dixit's farmhouse",
    images: [
      "/dixit-residence/01.jpeg",
      "/dixit-residence/02.jpeg",
      "/dixit-residence/03.jpeg",
      "/dixit-residence/04.jpeg",
      "/dixit-residence/05.jpeg",
    ],
    shortDescription: "2,800 sq.ft | Kolar | Karnataka",
    description:
      "Set amidst the peaceful mango groves of Kolar, this thoughtfully designed 3BHK villa stands as a testament to climate-responsive architecture. Built using Porotherm clay blocks, the home achieves a balance of thermal efficiency, visual warmth, and earthy elegance—making it both sustainable and striking. The villa’s massing is articulated through clean, geometric volumes, cascading terraces, and lush green planters integrated into the façade. A dramatic skylight-lit central court forms the heart of the home, drawing light and air deep into the interior spaces. Sleek black columns frame the front porch, which opens into a free-flowing interior layout designed for seamless indoor-outdoor connection. Large windows, deep overhangs, and vertical gardens enhance natural ventilation while softening the strong linear forms of the structure. The vertical block—crowned with a roof garden and open sit-out—anchors the overall form and houses a private upper-level retreat, offering views of the surrounding landscape. With its use of Porotherm blocks for insulation and durability, the home blends eco-sensitive construction with modern aesthetics—making it an ideal weekend haven or a quiet full-time escape into nature.",
    additionalInfo: {
      status: "In Progress",
      location: "Kolar",
      structure: "G+1",
      plotArea: "--",
      builtupArea: "2800 sq.ft",
      type: "Residential ",
      vastu: "Compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
];

export const interiorProjects = [
  {
    id: 8,
    name: "Mr. Sreekanth's residence",
    images: ["/jagadish-residence/01.jpg", "/jagadish-residence/02.jpg"],
    shortDescription: "1200 sq.ft | Bengaluru | Karnataka",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Provident eum explicabo, architecto assumenda inventore non earum cumque magnam facilis deserunt.",
    additionalInfo: {
      status: "Completed",
      location: "Ozone Urbana",
      structure: "G+2",
      plotArea: "1,200 sq.ft",
      builtupArea: "5,270 sq.ft",
      type: "Residential + Office Duplex",
      vastu: "compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 9,
    name: "Ms. Hari Priya's residence",
    images: [
      "/hp-residence/1.jpeg",
      "/hp-residence/1a.jpeg",
      "/hp-residence/2.png",
      "/hp-residence/2a.png",
      "/hp-residence/4.png",
      "/hp-residence/5.jpeg",
      "/hp-residence/6.png",
      "/hp-residence/7.png",
      "/hp-residence/8.png",
      "/hp-residence/9.png",
      "/hp-residence/10.png",
      "/hp-residence/11.jpeg",
      "/hp-residence/12.jpeg",
      "/hp-residence/13.jpeg",
    ],
    shortDescription: "1200 sq.ft | Bengaluru | Karnataka",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Provident eum explicabo, architecto assumenda inventore non earum cumque magnam facilis deserunt.",
    additionalInfo: {
      status: "Completed",
      location: "Ozone Urbana",
      structure: "G+2",
      plotArea: "1,200 sq.ft",
      builtupArea: "5,270 sq.ft",
      type: "Residential + Office Duplex",
      vastu: "compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
  {
    id: 10,
    name: "Ms. Pooja's residence",
    images: ["/jagadish-residence/01.jpg", "/jagadish-residence/02.jpg"],
    shortDescription: "1200 sq.ft | Bengaluru | Karnataka",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Provident eum explicabo, architecto assumenda inventore non earum cumque magnam facilis deserunt.",
    additionalInfo: {
      status: "Completed",
      location: "Ozone Urbana",
      structure: "G+2",
      plotArea: "1,200 sq.ft",
      builtupArea: "5,270 sq.ft",
      type: "Residential + Office Duplex",
      vastu: "compliant",
    },
    video: "",
    designHighlights: [],
    toolsUsed: [],
  },
];

export const graphicDesignProjects = [
  {
    id: 11,
    name: "Malt & Mash",
    images: ["/graphic-design/01.jpeg"],
    shortDescription: "Craft Beer Menu Design",
    description:
      "This sleek and contemporary drinks menu was crafted for Malt & Mash, a brewery-inspired outlet offering a premium lineup of craft beers. Designed with a clean layout and rustic-modern aesthetic, the menu appeals to casual drinkers and beer aficionados alike.",
    additionalInfo: null,
    designHighlights: [
      "Neutral woodgrain background evokes warmth and rustic authenticity, complementing the artisanal theme.",
      "Stylized script headers for beer names add character and highlight the uniqueness of each brew.",
      "Modern sans-serif body text ensures clarity and readability for quick glances.",
      "Price alignment keeps the layout organized and easy to scan.",
      "Vertical “SIPLIST” accent panel provides strong branding while balancing the visual structure.",
      "Subtle glassware illustrations enhance the thematic consistency.",
    ],
    video: "",
    toolsUsed: ["Adobe InDesign", "Adobe Illustrator", "Photoshop"],
  },
  {
    id: 12,
    name: "Intent & Impact",
    images: ["/graphic-design/02.jpeg"],
    shortDescription: "Visual Narrative",
    description:
      "A visual identity piece created for a 2022 sustainability awareness initiative. This design aimed to communicate the journey from environmental degradation to regeneration, encouraging community-led action for a sustainable future.",
    additionalInfo: null,
    designHighlights: [
      "Semi-circular motif symbolizing transformation: dry cracked earth to blooming greenery.",
      "Natural textures and organic elements to evoke environmental themes.",
      "Bold, centered typography for clarity and impact.",
      "Deep green background to represent harmony with nature.",
      "Messaging that aligns purpose with action.",
    ],
    video: "",
    toolsUsed: ["Adobe InDesign", "Adobe Illustrator"],
  },
  {
    id: 13,
    name: "Mother’s Day Sale– Promotional Graphic",
    images: ["/graphic-design/03.jpeg"],
    shortDescription: "Bold blooms meet bold deals.",
    description:
      "This vibrant promotional graphic celebrates Mother’s Day with a striking visual design aimed at maximizing user engagement. Featuring a limited-time 50% discount, the graphic blends floral elegance with bold messaging to capture attention across digital platforms.",
    designHighlights: [
      "Elegant floral framing enhances emotional connection and aligns with the celebratory theme.",
      "Bold white typography set against a warm coral background ensures high readability and visual impact.",
      "Handwritten script overlay adds a personal, heartfelt touch to the message.",
      "Prominent “Shop Now” call-to-action badge encourages immediate clicks and conversions.",
    ],
    additionalInfo: null,
    video: "",
    toolsUsed: ["Adobe InDesign", "Adobe Illustrator"],
  },
  {
    id: 14,
    name: "Identity – Branding for MARK STUDIO",
    images: ["/graphic-design/04.jpeg", "/graphic-design/05.jpeg"],
    shortDescription: "Precision. Vision. Identity.",
    description:
      "This sophisticated branding collateral was designed for MARK STUDIO, the architectural practice of Kiran Devalla, Principal Architect. With a refined visual language and a structured layout, the design expresses architectural clarity, elegance, and personal identity, aligning with the firm’s creative ethos.",
    designHighlights: [
      "Geometric linear motif in the background symbolizes structure, balance, and meticulous detailing—core principles of architecture.",
      "Bold typography for the studio name enhances legibility and projects confidence and professionalism.",
      "Minimalist contact layout on the business card ensures easy readability and quick reference.",
      "Clean monogram (K | D) logo reinforces personal branding while integrating harmoniously with the circular grid motif.",
      "Muted green-gray palette conveys calm, intelligence, and design sophistication.",
    ],
    additionalInfo: null,
    video: "",
    toolsUsed: ["Adobe InDesign", "Adobe Illustrator", "Photoshop"],
  },
  {
    id: 15,
    name: "Earth Investment Campaign – Awareness Graphic",
    images: ["/graphic-design/06.jpeg"],
    shortDescription: "Secure Tomorrow. Invest in Earth.",
    description:
      "This eco-centric promotional graphic supports a sustainability campaign designed to inspire environmental responsibility. Using sleek design elements and a QR code integration, it delivers a clean, modern message about green investment and planetary care.",
    designHighlights: [
      "Dynamic green gradient background evokes a sense of natural energy and growth while maintaining visual depth.",
      "Embedded QR code encourages user interaction, providing a seamless bridge to detailed content or donation platforms.",
      "Central leaf motif reinforces the campaign’s organic theme and highlights the QR code, symbolizing life and renewal.",
      "Bold, white serif typography in the lower-left corner contrasts effectively with the dark-to-light background shift, ensuring maximum legibility.",
      "Vertical bar accent adds a contemporary edge and balances the composition, leading the eye toward the campaign message.",
    ],
    additionalInfo: null,
    video: "",
    toolsUsed: ["Adobe InDesign", "Adobe Illustrator"],
  },
  {
    id: 16,
    name: "College Fest – Event Promo Graphic",
    images: ["/graphic-design/07.jpeg"],
    shortDescription: "Shaping the Future of Design",
    description:
      "This dynamic promotional graphic was designed to generate excitement for a college fest seminar exploring the future of design in the age of AI. With a high-impact visual and modern styling, it reflects the innovation, energy, and curiosity of the student community.",
    designHighlights: [
      "Vibrant, futuristic art backdrop symbolizes creative breakthroughs and technological evolution, aligning perfectly with the theme.",
      "Bold navy header block emphasizes the event’s theme and captures viewer attention instantly.",
      "Clean, high-contrast typography communicates the event’s focus and details with clarity and sophistication.",
      "Custom date badge styled in an abstract teal shape ensures quick visibility of event timing.",
      "Framed tech-inspired layout gives the poster a sleek, cutting-edge look ideal for a design-focused college crowd.",
      "Informative footer invites participants and links to the registration portal for easy access.",
    ],
    additionalInfo: null,
    video: "",
    toolsUsed: ["Adobe InDesign", "Adobe Illustrator"],
  },
];

export const allProjects = [
  ...exteriorProjects,
  ...interiorProjects,
  ...graphicDesignProjects,
];
